version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm i -g serverless
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - serverless deploy --stage $ENVIRONMENT --aws-s3-accelerate